sudo: required

node_js-steps: &node_js-steps
  language: node_js
  before_install:
    - if [[ `npm --version` != "6.4.1" ]]; then npm install -g npm@latest; npm --version; fi
  script: make travis
  after_success:
    - nvm version
    - if [[ ! -z "$DOCKER_USER" ]]; then docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && git checkout -- . && git clean -fd . && make docker_release; fi
  after_script: make report
  services:
    - docker
matrix:
  allow_failures:
    node_js: "node"
  include:
    - node_js: "10"
